### ISSUE TITLE
panic while calling vdf.ReadVdf

### ISSUE THREAD

**Issue by memob0x** [Wakeful-Cloud/vdf#1]
while i'm able to read file bytes with _os.ReadFile_, as in your example, calling _vdf.ReadVdf_ causes the following panic for me:

```
"runtime error: index out of range [125] with length 125"
Stack:
	 3  0x000000000052c1be in github.com/wakeful-cloud/vdf.nextStringZero
	     at /home/dono/go/pkg/mod/github.com/wakeful-cloud/vdf@v0.0.0-20210218214150-0be6ec18b390/vdf.go:149
	 4  0x000000000052ba39 in github.com/wakeful-cloud/vdf.nextMapItem
	     at /home/dono/go/pkg/mod/github.com/wakeful-cloud/vdf@v0.0.0-20210218214150-0be6ec18b390/vdf.go:92
	 5  0x000000000052b71c in github.com/wakeful-cloud/vdf.nextMap
	     at /home/dono/go/pkg/mod/github.com/wakeful-cloud/vdf@v0.0.0-20210218214150-0be6ec18b390/vdf.go:59
	 6  0x000000000052b5fe in github.com/wakeful-cloud/vdf.ReadVdf
	     at /home/dono/go/pkg/mod/github.com/wakeful-cloud/vdf@v0.0.0-20210218214150-0be6ec18b390/vdf.go:49
```

i'm using golang 1.18 in WSL, latest steam client on windows

**Comment by Wakeful-Cloud** [comment]
It appears that the string near the 124th character isn't [null-terminated](https://en.wikipedia.org/wiki/Null-terminated_string). Are you sure this is a binary VDF and not a [text VDF](https://developer.valvesoftware.com/wiki/KeyValues#Example)? Could you possibly upload the VDF? (If you redact anything, just be sure to not alter the control characters).

**Comment by memob0x** [comment]
I'm trying to open steam libraryfolders.vdf file

**Comment by Wakeful-Cloud** [comment]
On my installation, `C:\Program Files (x86)\Steam\steamapps\libraryfolders.vdf` contains:
```
"libraryfolders"
{
	"0"
	{
		"path"		"C:\\Program Files (x86)\\Steam"
		"label"		""
		"contentid"		"[Redacted]"
		"totalsize"		"0"
		"update_clean_bytes_tally"		"0"
		"time_last_update_corruption"		"0"
		"apps"
		{
		}
	}
}
```
This is a text VDF, not a binary VDF.

**Comment by Wakeful-Cloud** [comment]
You probably want something like [Andy Grunwald's VDF library](https://github.com/andygrunwald/vdf) instead. I never bothered adding text-based VDF support to this, since I didn't need it for my own project ([Aluminum](https://github.com/wakeful-cloud/aluminum)) and there were a few text-based VDF parsers for Go already out there. I may add support in the future to turn this into a unified binary and text-based VDF library, but it's not a super high priority for me right now (PRs are welcome though).

**Comment by memob0x** [comment]
Thank you for the explanation
